import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";

import Navbar from "./Navbar";
import Sidebar from "./Sidebar";

import "./css/globals.css";

config.autoAddCss = false;

export const metadata = {
  title: "To Do App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <section className=" mx-4 my-6">{children}</section>
      </body>
    </html>
  );
}
